---
- name: Setup vprofile Bastion Host
  hosts: localhost
  connection: local
  gather_facts: no 
  tasks:
    - name: Import Bastion Host setup variables
      include_vars: vars/bation_setup

    - name: Import Bastion Host setup variables
      include_vars: vars/output_vars

    - name: create a new ec2 key pair, returns generated private key
      ec2_key:
        name: bastion_key
        region: "{{region}}"
      register: keyout

    - name: store login key
      copy:
        content: "{{ keyout.key.private_key }}"
        dest: ./bastion_key.pem
        mode: 0600
      when: keyout.changed

    - name: Create Security group for Bastion Host
      ec2_group:
        name: bastion-host-sg
        description: Allow port 22 anywhere
        region: "{{region}}"
        vpc_id: "{{vpcid}}"   
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MY_IP}}"
      register: BastionSG_out

    - name: creating bastion host
      ec2:
        key_name: bastion_key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Bastion_host1"
          Project: Vprofile1
          Owner: Devops Team1
        exact_count: 1
        count_tag:
          Name: "Bastion_host1"
          Project: Vprofile1
          Owner: Devops Team1
        group_id: "{{BastionSG_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionHost_out    
